### PR TITLE
Rspec User Model

### PR DESCRIPTION
**Pull request by ghost**
## Related Tickets
- [#44254](https://edu-redmine.sun-asterisk.vn/issues/44254)

## WHAT
- write rspec modle user

## HOW

1. gem "database_cleaner"
2. gem "factory_bot_rails"
3. gem "shoulda-matchers"

## Evidence (Screenshot or Video)
Screenshot from 2021-12-15 22-26-13

### CODE REVIEW

**Comment by ghost** [comment]
ready

**Review by ghost — COMMENTED** [review]
up cái ảnh lên em

**Comment by ghost** [comment]
Screenshot from 2021-12-16 09-23-40

**Comment by ghost** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
