### PR TITLE
User view history order, User view order detail, User cancel order

### PR DESCRIPTION
**Pull request by ghost**
https://edu-redmine.sun-asterisk.vn/issues/43961
https://edu-redmine.sun-asterisk.vn/issues/43962
https://edu-redmine.sun-asterisk.vn/issues/44006

### CODE REVIEW

**Comment by ghost** [comment]
Screenshot from 2021-12-09 08-29-38

**Comment by ghost** [comment]
Screenshot from 2021-12-09 08-29-54

**Comment by ghost** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
